### PR TITLE
Bug fix for decompiler section offset 

### PR DESCRIPTION
**Pull request by herrcore**
Section offset wasn't populated in decompiler object.

### CODE REVIEW

**Comment by c3rb3ru5d3d53c** [comment]
Changed PR base to `staging` branch for QA

**Comment by c3rb3ru5d3d53c** [comment]
image

Can confirm the offsets are working as expected :smile:

**Comment by c3rb3ru5d3d53c** [comment]
Hey @emgon, were  you able to confirm the offsets are looking fine?

**Comment by emgon** [comment]
> Hey @emgon, were you able to confirm the offsets are looking fine?

Yes, I tested using your script.

image
image

**Pull request merged**
