### PR TITLE
Add packaging sources to create .deb-files

### PR DESCRIPTION
**Pull request by jgru**
Dear @c3rb3ru5d3d53c, 

this PR adds the necessary packaging sources for building Debian binary packages of the programs/libs 
- `libbinlex`
- `binlex`
- `blyara`

in order to ease installation and package removal. 

As it is described in the updated `README.md`-file, users can simply run `make deb` to create those `.deb`-files, which uses `dpkg-buildpackage` under the hood. 

Please note, that for `blyara`, an unnecessary dependency on `libcapstone` has been removed.
Packaging the development-files as `libbinlex-dev` has not been done yet. 
 
Thanks already in advance for considering this PR.

Best regards,
jgru

### CODE REVIEW

**Comment by c3rb3ru5d3d53c** [comment]
Having a look here in a minute :)

**Comment by c3rb3ru5d3d53c** [comment]
So I tested this and it works, however would it be possible to have the files go into the `build/` folder instead of `..` which goes outside of the context of binlex repo?

**Comment by c3rb3ru5d3d53c** [comment]
```cmake
cmake_minimum_required(VERSION 3.5)

set(VERSION_MAJOR 1)
set(VERSION_MINOR 1)
set(VERSION_PATCH 1)
set(GLOBAL_VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH})

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")

project(binlex
    VERSION ${GLOBAL_VERSION}
    DESCRIPTION "A Binary Genetic Traits Lexer and C++ Library"
)

add_library(binlex SHARED
    src/args.cpp
    src/raw.cpp
    src/common.cpp
    src/blelf.cpp
    src/pe.cpp
    src/decompiler.cpp
    src/sha256.c
)

set_target_properties(binlex PROPERTIES SOVERSION ${GLOBAL_VERSION})

add_library(binlex::library ALIAS binlex)

target_include_directories(binlex
    PUBLIC
        ${PROJECT_SOURCE_DIR}/include
)

add_executable(binlex-bin
    src/binlex.cpp
)

target_link_libraries(binlex-bin
    PRIVATE
        binlex::library
    PUBLIC
        -lcapstone
        -lm
        -lpthread
)

set_target_properties(binlex-bin
    PROPERTIES OUTPUT_NAME binlex
)

install(TARGETS binlex-bin DESTINATION bin)

install(TARGETS binlex
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})

project(blyara
    VERSION ${GLOBAL_VERSION}
    DESCRIPTION "A Binlex Yara Generation Utility"
)

set(SOURCES_BLYARA
    src/blyara.cpp
)

add_executable(blyara ${SOURCES_BLYARA})

target_link_libraries(blyara -lm)

target_include_directories(blyara
    PRIVATE
        ${PROJECT_SOURCE_DIR}/include
)

install(TARGETS blyara DESTINATION bin)

add_custom_target(uninstall
    "${CMAKE_COMMAND}" -P "${CMAKE_MODULE_PATH}/uninstall.cmake"
)

SET(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME binlex)
set(CPACK_PACKAGE_DESCRIPTION "A Binary Genetic Traits Lexer and C++ Library")
set(CPACK_RESOURCE_FILE_LICENSE "")
set(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "@c3rb3ru5d3d53c")
set(CPACK_PACKAGE_CONTACT "c3rb3ru5d3d53c@protonmail.com")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libcapstone-dev")
include (CPack)
```

**Comment by c3rb3ru5d3d53c** [comment]
If we use `cmake` and `cpack` for deb build it will put a single package with the lib, binlex binary and blyara tool in the `build/` folder. Also easier to maintain :)

**Comment by jgru** [comment]
Hi, thanks for having a look at my PR. Debian policy expects a subdirectory
named `debian` under the programs top-level source directory. (See
https://www.debian.org/doc/manuals/maint-guide/dreq.en.html) I'm not aware
of a way of changing this using `dpkg-buildpackage`. (Does anybody know
better?)

However, if you do not want to keep the `debian`- directory containing all
the packaging files at the repo's top level, a workaround could be to place
it in a subdirectory and use the Makefile target to move it temporarily for
building the package and then moving it back into the subdir.

What do you think?

Best regards,
jgru

**Comment by jgru** [comment]
`cmake` is already used (implicitly) by debhelper. (See `debian/rules`)
If you just want to host some .debs on the repo's release-page and don't
intend to upload the .dsc- and .deb-files into the official
package-archives, this is a convenient way of doing it. However, I'm pretty
sure, that the results of `cpack` won't fulfill the package archives
requirements.

If you prefer that, that's fine for me, then I'll keep the newly created
packaging files in the Debian's salsa-repo. Just let me know.

Best regards,
jgru

**Comment by c3rb3ru5d3d53c** [comment]
image

**Comment by c3rb3ru5d3d53c** [comment]
we can still include the `debian` folder if it's required in the top level source directory.

**Comment by c3rb3ru5d3d53c** [comment]
I see no reason why we cannot have the best of both worlds :)

**Comment by jgru** [comment]
> I see no reason why we cannot have the best of both worlds :)

I had a second thought about that. I think, it might be a better option to use `cpack` for build the .debs for the repo's release-page and do not version the `debian` subdirectory within here, but within the already mentioned salsa. It will make the actual packagin work more easy and since you found `cpack` an apt solution for distributing .debs here, this might be preferable. 
So, I'm kindly asking for reverting the merge and closing the PR. Sorry for this reconsideration, but I think, it brought `binlex` a bit forward and the source-files submitted by me will still be used in the future.  

Best regards
jgru

**Pull request merged**
