### PR TITLE
Enter the matrix

### PR DESCRIPTION
**Pull request by mrexodia**

### CODE REVIEW

**Comment by c3rb3ru5d3d53c** [comment]
Nice, we able to do an if statement here to see if the branch is master we always perform a build?

**Comment by mrexodia** [comment]
I think this will work. The trick is to use a helper variable in the matrix (I called it `target`) and not the OS itself (since you might want to for example compile with both clang and gcc on the same OS):

```yml
      matrix:
        target:
          - ubuntu
          - windows
          - macos
```

The relevant documentation is [here](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-single-dimension-matrix), except I use an expanded list instead of the `[]` syntax. The main `target` variable can be expanded with `${{ matrix.target }}` and the `include` variables are also included in the matrix (for example the target `ubuntu` has `${{ matrix.os }}` == `ubuntu-latest`):

```yml
        include:
          - target: ubuntu
            os: ubuntu-latest
            build-type: Release
            # You can add flags separated by newlines here
            extra-cmake-flags: >-
              "-DBUILD_PYTHON_BINDINGS=ON"
          - target: windows
            os: windows-latest
            build-type: Release
            extra-cmake-flags: >-
              "-DBUILD_PYTHON_BINDINGS=ON"
          - target: macos
            os: macOS-latest
            build-type: Release
            extra-cmake-flags: >-
              "-DBUILD_PYTHON_BINDINGS=ON"
```

The `${{ matrix.target }}` can be used in `if` statements and it's also used in the artifact name:

```yml
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.target }}
        path: build/install/bin/*
```

**Comment by c3rb3ru5d3d53c** [comment]
Appears this might be what I'm looking for `github.ref == 'refs/heads/master'`

**Comment by c3rb3ru5d3d53c** [comment]
`if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) || github.ref == 'refs/heads/master'}}`

**Comment by mrexodia** [comment]
The whole pipeline will run for every push (on any branch) and on any pull request. If you want to skip it you can put `[skip ci]` in your commit message (https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs)

**Comment by mrexodia** [comment]
There's no need to do anything specifically with `github.ref`

**Comment by mrexodia** [comment]
Also if you push a tag called `v1.1.1` it will automatically create a GitHub release and upload the zipped artifacts from every pipeline to the release. To create a prerelease you can do `v1.1.1-pre`

**Comment by c3rb3ru5d3d53c** [comment]
Nice, yeah I'm sold this will be a good move, it consolidates everything right here in github making things easier longer term.

**Comment by mrexodia** [comment]
Yeah totally agreed, I'm slowly upgrading this GitHub Actions script for CMake and you can copy paste it in pretty much any repo without any changes ^^

**Comment by c3rb3ru5d3d53c** [comment]
> Yeah totally agreed, I'm slowly upgrading this GitHub Actions script for CMake and you can copy paste it in pretty much any repo without any changes ^^

That's awesome, anything to make lives easier, guess Microsoft is really leveraging their azure cloud for this stuff.

**Comment by c3rb3ru5d3d53c** [comment]
That being said we are missing now a few artifacts for things now and we don't execute `cpak` I'll see what I can do there

**Comment by mrexodia** [comment]
Yeah I only add the `build/install/bin` folder to the artifacts, but that's easily fixed of course 🙂

**Pull request merged**
