### PR TITLE
Compile on MSVC

### LINKED ISSUE #38: Windows: CMake Parameter Issue
This parameter "CMAKE_CXX_FLAGS_RELEASE:STRING=" is inside C/C++ compiling options and breaks IntelliSense of VisualStudio, removing it manually fix the problem. trying to understand how to remove it.

### LINKED ISSUE #128: Fix Windows Build Support
**Is your feature request related to a problem? Please describe.**
Support for Windows build again.

**Describe the solution you'd like**
Operational windows build.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mrexodia**
Unfortunately the CMake is a bit hacky so the fixes are also a bit hacky. In my opinion `ExternalProject_Add` should eventually be replaced with `find_package` (in combination with vcpkg), but LIEF/tlsh (and older versions of capstone) don't have proper packages so this is rather tricky to do for now. Another issue is that there is no support for multi-config generators (like Visual Studio or Ninja) so you might end up with errors trying to build anything but `Release`.

I forked tlsh to https://github.com/mrexodia/tlsh with some changes to the `CMakeLists.txt` to make it work on Windows. The repo seems rather dead so I don't think trying to get this upstream will be successful. Feel free to fork it to your account.

image

Closes #126
Closes #38
Closes #128

### CODE REVIEW

**Comment by c3rb3ru5d3d53c** [comment]
@jbx81-1337 are you able to review this PR, test on your Windows system?

I have to spin up a Windows VM here :smile:

**Comment by jbx81-1337** [comment]
On my windows system i got:
`Error	D8016	'/O2' and '/RTC1' command-line options are incompatible	binlex`  On binlex.vcxproj, tlsh seems to work, but you need to cleanup the repository because contains 5 PDFs in \build\tlsh\src\tlsh and binlex will download that to compile.

**Comment by mrexodia** [comment]
Yeah, Debug mode doesn’t work because of the ExternalProject as discussed. Release should work fine though.

**Comment by mrexodia** [comment]
Thanks for the info, I’ll try to find the equivalent CMake. The problem though is that binlex will be in Debug mode, but you will not be able to debug the dependencies

**Comment by jbx81-1337** [comment]
Also check on your branch seems you have uploaded 5 PDFs on src/tlsh folder

**Comment by mrexodia** [comment]
Those are part of the original repository too.

**Comment by mrexodia** [comment]
I’ll take a look, something strange appears to be going on there actually. Thanks for letting me know!

**Comment by c3rb3ru5d3d53c** [comment]
@jbx81-1337 Perhaps this will work?

```cmake
macro(RemoveDebugCXXFlag flag)
    string(REPLACE "${flag}" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
endmacro()
RemoveDebugCXXFlag("/RTC1")
```

Reference: https://stackoverflow.com/questions/32945670/set-compiler-option-to-default-in-cmake

**Comment by mrexodia** [comment]
In general it’s bad practice to change any variable that starts with `CMAKE_` but maybe there is no other way…

**Comment by c3rb3ru5d3d53c** [comment]
> In general it’s bad practice to change any variable that starts with `CMAKE_` but maybe there is no other way…

Yeah, I'll keep looking to see what can be done there, not sure if there is an alternative.

**Comment by mrexodia** [comment]
Alright I pushed an update. Thanks @c3rb3ru5d3d53c and @jbx81-1337 for the suggestions, I hope this will work now ^^

**Comment by mrexodia** [comment]
Also I forgot to say, but I had to upgrade LIEF to support MSVC so this would close #126

**Comment by c3rb3ru5d3d53c** [comment]
> Also I forgot to say, but I had to upgrade LIEF to support MSVC so this also closes #126

Hey @mrexodia, this is great!

@jbx81-1337, you able to do some windows build testing for this?

I'll also attach issue #126 to this PR.

**Comment by jbx81-1337** [comment]
Yep I can check on the next hours (damn timezone)

**Comment by mrexodia** [comment]
I think I fixed the CI and added AppVeyor builds for Windows.

**Comment by c3rb3ru5d3d53c** [comment]
I'm checking the windows build for this now :smile:

**Comment by c3rb3ru5d3d53c** [comment]
I'm checking the windows build for this now :smile:

**Comment by c3rb3ru5d3d53c** [comment]
So the build for this is in much a better state then previously, as mentioned we still have a bit of a hack to get the Windows build working. But we can make another issue for us to migrate from using `ExternalProject_Add` to `findpackage`.  We will need to add git submodules for `LIEF`, `tlsh`, and `capstone`, but this shouldn't be too much of an issue.

**Pull request merged**
